# Generated by Django 5.0.4 on 2024-04-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaJuego',
            fields=[
                ('id_categoria', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código categoría')),
                ('nombre_categoria', models.CharField(max_length=50, verbose_name='Nombre categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código perfil')),
                ('nombre_perfil', models.CharField(max_length=50, verbose_name='Nombre perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id_juego', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre_juego', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion_juego', models.CharField(max_length=200, verbose_name='Descripción')),
                ('url_img_juego', models.CharField(max_length=50, verbose_name='URL imagen')),
                ('precio_juego', models.IntegerField(verbose_name='Precio')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriajuego')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección despacho')),
                ('id_perfil', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.perfil')),
            ],
        ),
    ]
