# Generated by Django 5.0.4 on 2024-04-10 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección despacho')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca de Vehículo')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('imagen', models.ImageField(upload_to='vehiculos/', verbose_name='Imagen del vehículo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
