# Generated by Django 5.0.4 on 2024-04-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_perfil',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.perfil'),
        ),
    ]
