# Generated by Django 5.0.4 on 2024-04-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen_juego',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen del juego'),
        ),
    ]
