# Generated by Django 5.0.4 on 2024-04-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_categoria_idcategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaJuego',
            fields=[
                ('id_categoria', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código categoría')),
                ('nombre_categoria', models.CharField(max_length=50, verbose_name='Nombre categoría')),
            ],
        ),

    ]
