# Generated by Django 5.0.4 on 2024-04-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_vehiculo_categoria_juego_delete_categoria_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='juego',
            name='descripcion_juego',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),

    ]
