# Generated by Django 5.0.4 on 2024-04-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_vehiculo_categoria_and_more'),
    ]

    operations = [

    ]
