# Generated by Django 5.0.4 on 2024-04-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_vehiculo_categoria_delete_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código perfil')),
                ('nombre_perfil', models.CharField(max_length=50, verbose_name='Nombre perfil')),
            ],
        ),
    ]
